services:
  php:
    build:
      context: .
      dockerfile: php.dockerfile
    container_name: php
    volumes:
      - ./serveur_php/html:/var/www/html
    ports:
      - 8080:80
      
  mysql:
    build: 
      context: .
      dockerfile: mysql.dockerfile
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_telegraph
    volumes:
      - mysql_data:/var/lib/mysql
      - ./serveur_mysql/setup_telegraph_db.sql:/docker-entrypoint-initdb.d/1_setup_telegraph_db.sql
    ports:
      - 3306:3306
volumes:
  mysql_data: