services:
  toolkit:
    build: 
      context: .
      dockerfile: toolkit.dockerfile
    container_name: toolkit
    networks:
      - toolkit_network
    tty: true  # Permet d'avoir un terminal interactif
    depends_on:
      - toolkit2

  toolkit2:
    build:
      context: .
      dockerfile: toolkit2.dockerfile
    container_name: toolkit2
    networks:
      - toolkit_network
    ports:
      - "22:22"   # SSH
      - "80:80"   # HTTP
      - "443:443" # HTTPS
      - "5201:5201" # iperf3
    tty: true

networks:
  toolkit_network:
    driver: bridge
